---
fail2ban_uninstall: false

fail2ban_max_retry: 3
fail2ban_ban_time: 24h
fail2ban_find_time: 30m
fail2ban_ignore_ips:
  - 127.0.0.1/8
  - ::1
fail2ban_ban_time_increment: true
fail2ban_ban_time_multipliers: "1 2 4 8 16 32 64"
fail2ban_ban_time_max: 168h

fail2ban_extra_jails:
  - name: sshd
    settings:
      enabled: true
      backend: systemd
      port: "22"
      mode: aggressive
