---
namespace: christopherbstocks
name: pulsar_pki
version: 0.0.0
readme: ../../README.md
license_file: ../../LICENSE.md
authors:
  - Christopher Stocks <christopher.stocks@protonmail.ch>
description: Ansible collection for Linux PKI and certificate lifecycle management.
tags:
  - linux
  - pki
repository: https://github.com/ChristopherBStocks/Pulsar
dependencies: {}
build_ignore: []
