---
namespace: christopherbstocks
name: pulsar_networking
version: 0.2.1
readme: ../../README.md
license_file: ../../LICENSE.md
authors:
  - Christopher Stocks <christopher.stocks@protonmail.ch>
description: Ansible collection for Linux network services including SSH hardening, load balancing, and mesh VPN.
tags:
  - linux
  - networking
repository: https://github.com/ChristopherBStocks/Pulsar
dependencies: {}
build_ignore: []
