---
- name: Fail2Ban >> RedHat | Install package
  become: true
  tags: [fail2ban, install]
  ansible.builtin.dnf:
    name: fail2ban
    state: present
  notify: Fail2Ban | Restart

- name: Fail2Ban >> RedHat | Deploy jail.local
  become: true
  tags: [fail2ban, install]
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Fail2Ban | Restart

- name: Fail2Ban >> RedHat | Deploy extra jails
  become: true
  tags: [fail2ban, install]
  when: fail2ban_extra_jails | length > 0
  ansible.builtin.template:
    src: jail.extra.j2
    dest: /etc/fail2ban/jail.d/extra.local
    owner: root
    group: root
    mode: "0644"
  notify: Fail2Ban | Restart

- name: Fail2Ban >> RedHat | Remove extra jails
  become: true
  tags: [fail2ban, install]
  when: fail2ban_extra_jails | length == 0
  ansible.builtin.file:
    path: /etc/fail2ban/jail.d/extra.local
    state: absent
  notify: Fail2Ban | Restart

- name: Fail2Ban >> RedHat | Ensure running
  become: true
  tags: [fail2ban]
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true
