---
- name: firewalld | Install
  become: true
  tags: [firewalld, install]
  ansible.builtin.package:
    name: firewalld
    state: present

- name: firewalld | Activate
  become: true
  tags: [firewalld, install]
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
    daemon_reload: false

- name: firewalld | Purge Rules
  tags: [firewalld, purge, rules]
  ansible.builtin.include_tasks: purge.yml

- name: firewalld | Configure Rules
  tags: [firewalld, configure, rules]
  ansible.builtin.include_tasks: rules.yml

- name: firewalld | Configure Forwards
  tags: [firewalld, configure, forwards]
  ansible.builtin.include_tasks: forwards.yml

- name: firewalld | Reload
  become: true
  tags: [firewalld, reload]
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
